name = "JuliaDevPackage"
uuid = "60cfa035-9d76-412c-a3c7-deefc9d27c44"
authors = ["fcriscuo <genomicdatasci@gmail.com>"]
version = "0.1.0"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
StaticArrays = "1.5.11"
